---
- hosts: all
  become: true
  tasks:
  - name: 'Fetch the file from the WSUS server to master'
    ansible.builtin.fetch:
      src: '{{item}}'
      dest: 'C:\Users\MohamedAminNASRI\Desktop\'
    with_fileglob:
    - 'C:\Users\Administrateur\Desktop\*'
