---
- hosts: all
  become: true
  tasks:
  - name: show
    ansible.windows.win_find:
      paths: 'C:\Users\Administrateur\Desktop\'
  - name: 'Fetch the file from the WSUS server to master'
    ansible.builtin.fetch:
      src: '{{ item }}'
      dest: 'C:\Users\MohamedAminNASRI\Desktop\'
    with_fileglob:
    - 'C:\Users\Administrateur\Desktop\'
  - debug: 
      msg: 'error with {{item}}'
    with_fileglob: 'C:\Users\Administrateur\Desktop\'
