---
- hosts: all
  become: true
  tasks:
  - name: show
    ansible.windows.win_find:
      paths: 'C:\Users\Administrateur\Desktop\'
    register: file_list
  - name: 'Fetch the file from the WSUS server to master'
    ansible.builtin.fetch:
      src: '{{ item.path }}'
      dest: 'files/'
      flat: yes
    with_items: 
    - "{{file_list.files}}"
  - debug: 
      msg: "error with {{item}}"
    with_items: 
    - "{{file_list.files}}"
  - ansible.builtin.find:
      paths: 'files/'
    delegate_to: localhost
